---
- hosts: app
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy welcome page to nginx
      copy:
        src: welcome.html
        dest: /var/www/html/welcome.html

    - name: Create nginx configuration file
      copy:
        dest: /etc/nginx/sites-available/myapp
        content: |
          server {
            listen 80;
            server_name localhost;

            location / {
              root /var/www/html;
              index welcome.html;
            }

            access_log /var/log/nginx/myapp_access.log;
            error_log /var/log/nginx/myapp_error.log;
          }

    - name: Enable configuration
      file:
        src: /etc/nginx/sites-available/myapp
        dest: /etc/nginx/sites-enabled/myapp
        state: link

    - name: Restart nginx
      service:
        name: nginx
